# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

variables:
  imageName: "service-tracker-ui:$(build.buildId)"
  acrName: cbtacr

steps:
  - script: |
      docker build -f Dockerfile -t $(acrName).azurecr.io/$(imageName) .
      docker login -u $(acrName) -p $pswd $(acrName).azurecr.io
      docker push $(acrName).azurecr.io/$(imageName)
    env:
      pswd: $(dockerPassword)
    displayName: "Build and push Docker image"
